# ----------------------------------------------------------
# QC and Diagnostic Figures
# Author: Funmi Oyebamiji
# Depends on: load_libraries.R, functions.R (sourced by run.sh)
# Note: These figures are diagnostic/exploratory — not shown in manuscript.
#       Manuscript figures are generated by figure_script_2.R (Ela Pask).
# ----------------------------------------------------------

if (!exists("dataDir"))   source("/code/load_libraries.R")
if (!exists("save_pptx")) source("/code/functions.R")

# Load objects saved by analysis.R
xen_integrated <- readRDS(file.path(resultsDir, "Seurat_object.rds"))

# ── Per-sample VlnPlots (before QC filter) ───────────────────────────────────
# Reload individual sample RDS files saved during loading loop
xfiles     <- list.files(dataDir, pattern = "Changelater")
sample_ids <- sapply(xfiles, function(i) {
  gsub("-", ".", strsplit(gsub("Changelater", "", i), "__")[[1]][3])
})

for (j in sample_ids) {
  obj <- readRDS(file.path(resultsDir, paste0(j, ".rds")))
  png(file.path(resultsDir, paste0("VlnPlotbeforefilter_", j, ".png")),
      height = 9, width = 13, units = "in", res = 300)
  print(VlnPlot(obj, features = c("nFeature_Xenium", "nCount_Xenium"),
                layer = "counts", ncol = 2, pt.size = 0, raster = FALSE))
  dev.off()
}
message("QC VlnPlots saved...")

# ── Unintegrated UMAP — coloured by sample ───────────────────────────────────
save_dimplot(xen_integrated,
             filename  = file.path(resultsDir, "DimPlot.umap.unintegrated.png"),
             reduction = "umap.unintegrated", group_by = "sample",
             cols = sample_colors, raster = FALSE, label = TRUE)

# ── Harmony UMAP — coloured by cluster ───────────────────────────────────────
save_dimplot(xen_integrated,
             filename  = file.path(resultsDir, "DimPlot.umap.original.png"),
             reduction = "umap", group_by = "runharmony_clusters",
             cols = cluster_colors, raster = FALSE, label = TRUE)

# ── Subclustered UMAP ────────────────────────────────────────────────────────
save_dimplot(xen_integrated,
             filename  = file.path(resultsDir, "DimPlot.umap.combined.png"),
             reduction = "umap", group_by = "runharmony_combined",
             cols = cluster_colors, raster = FALSE, label = TRUE)

# ── SingleR annotation UMAPs ─────────────────────────────────────────────────
for (ref_name in c("hpca", "blueE")) {
  save_dimplot(xen_integrated,
               filename   = file.path(resultsDir, paste0("DimPlot.umap.", ref_name, ".png")),
               reduction  = "umap",
               group_by   = paste0(ref_name, "_cellmain"),
               cols       = singler_colors,
               raster     = FALSE,
               label      = TRUE,
               label_size = 3)
}

# ── Cell type UMAP — with legend (only version used) ─────────────────────────
umap_theme <- list(
  ggplot2::ggtitle("UMAP by Cell Type"),
  ggplot2::xlab("UMAP1"), ggplot2::ylab("UMAP2"),
  ggplot2::theme(plot.title = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5))
)
p <- DimPlot(xen_integrated, reduction = "umap", group.by = "Celltypes",
             cols = cell_colors, raster = FALSE, label = TRUE, label.size = 4) +
     umap_theme
ggplot2::ggsave(file.path(resultsDir, "DimPlot.umap.celltypes.WiLegend.png"),
                p, height = 9, width = 13, units = "in", dpi = 300)

message("All QC figures saved to /results/")
